---

- name: Creating glance database
  mysql_db:
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    login_host: "{{ database_address }}"
    login_port: "{{ mariadb_port }}"
    name: "{{ glance_database_name }}"
    state: "present"
  run_once: True
  delegate_to: "{{ groups['glance-api'][0] }}"

- name: Grant access to the DB for the service
  mysql_user:
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    login_host: "{{ database_address }}"
    login_port: "{{ mariadb_port }}"
    name: "{{ glance_database_user }}"
    password: "{{ glance_database_password }}"
    host: "{{ item }}"
    state: "present"
    priv: "{{ glance_database_name }}.*:ALL"
  with_items:
    - "localhost"
    - "%"
  run_once: True
  delegate_to: "{{ groups['glance-api'][0] }}"

- name: Perform a Glance DB sync
  shell: glance-manage db_sync && glance-manage db_load_metadefs
  become: yes
  become_user: glance
  changed_when: False
  run_once: True
  delegate_to: "{{ groups['glance-api'][0] }}"
