---

- name: Ensuring ceph config directory exists
  file:
    path: "/etc/ceph"
    state: directory
  when: inventory_hostname in groups['glance-api']

- name: Apply ceph config
  template:
    src: "{{ role_path }}/../ceph/templates/ceph.conf.j2"
    dest: "/etc/ceph/ceph.conf"
    owner: "ceph"
    group: "ceph"
    mode: "0644"
  when: inventory_hostname in groups['glance-api']

- include: ../../ceph_pools.yml
  vars:
    pool_name: "{{ glance_pool_name }}"
    pool_type: "{{ glance_pool_type }}"
    cache_mode: "{{ glance_cache_mode }}"

- name: Pulling cephx keyring
  command: |
      ceph auth get-or-create client.glance mon 'allow r' \
           osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ ceph_glance_pool_name }}, allow rwx pool={{ ceph_glance_pool_name }}-cache'
  register: cephx_key
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  changed_when: False
  run_once: True

- name: Pushing cephx keyring
  copy:
    content: "{{ cephx_key.stdout }}\n\r"
    dest: "/etc/ceph/ceph.client.glance.keyring"
    mode: "0644"
  when: inventory_hostname in groups['glance-api']
