---
- name: Creating the Glance service and endpoint
  os_keystone_service:
      service_name: "glance"
      service_type: "image"
      description: "Openstack Image"
      endpoint_region: "{{ openstack_region_name }}"
      url: "{{ item.url }}"
      interface: "{{ item.interface }}"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ openstack_auth }}"
      endpoint_type: admin
  register: glance_endpoint
  until: glance_endpoint|success
  retries: 3
  delay: 5
  run_once: True
  with_items:
    - {'interface': 'admin', 'url': '{{ glance_admin_endpoint }}'}
    - {'interface': 'internal', 'url': '{{ glance_internal_endpoint }}'}
    - {'interface': 'public', 'url': '{{ glance_public_endpoint }}'}

- name: Creating the Glance project, user, and role
  os_keystone_user:
      project: "service"
      user: "{{ glance_keystone_user }}"
      password: "{{ glance_keystone_password }}"
      role: "admin"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ openstack_auth }}"
      endpoint_type: admin
  register: glance_user
  until: glance_user|success
  retries: 3
  delay: 5
  run_once: True
