---

- name: Install glance packages
  package:
    name: "{{ item }}"
    state: "{{ glance_package_state }}"
  register: install_packages
  until: install_packages | success
  retries: 5
  delay: 2
  with_items: "{{ glance_distro_packages }}"
