---
- name: Creating Cinder database
  mysql_db:
    login_host: "{{ database_address }}"
    login_port: "{{ mariadb_port }}"
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    name: "{{ cinder_database_name }}"
  run_once: True
  delegate_to: "{{ groups['cinder-api'][0] }}"

- name: Creating Cinder database user and setting permissions
  mysql_user:
    login_host: "{{ database_address }}"
    login_port: "{{ mariadb_port }}"
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    name: "{{ cinder_database_name }}"
    password: "{{ cinder_database_password }}"
    host: "%"
    priv: "{{ cinder_database_name }}.*:ALL"
    append_privs: "yes"
  run_once: True
  delegate_to: "{{ groups['cinder-api'][0] }}"

- name: Perform a Cinder DB sync
  shell: cinder-manage db sync
  changed_when: False
  become: yes
  become_user: cinder
  run_once: True
  delegate_to: "{{ groups['cinder-api'][0] }}"

