---

- name: Install cinder packages
  package:
    name: "{{ item }}"
    state: "{{ cinder_package_state }}"
  register: install_packages
  until: install_packages | success
  retries: 5
  delay: 2
  with_items: "{{ cinder_distro_packages }}"

