---

- name: Install rally packages
  package:
    name: "{{ item }}"
    state: "{{ rally_package_state }}"
  register: install_packages
  until: install_packages | success
  retries: 5
  delay: 2
  with_items: "{{ rally_distro_packages }}"
