---

- name: Creating Rally databases
  mysql_db:
    login_host: "{{ database_address }}"
    login_port: "{{ mariadb_port }}"
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    name: "{{ rally_database_name }}"
  run_once: True
  delegate_to: "{{ groups['rally'][0] }}"

- name: Creating Rally databases user and setting permissions
  mysql_user:
    login_host: "{{ database_address }}"
    login_port: "{{ mariadb_port }}"
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    name: "{{ rally_database_user }}"
    password: "{{ rally_database_password }}"
    host: "%"
    priv: "{{ rally_database_name }}.*:ALL"
    append_privs: "yes"
  run_once: True
  delegate_to: "{{ groups['rally'][0] }}"

- name: Perform a Rally DB sync
  shell: rally-manage db create || rally-manage db upgrade
  changed_when: False
  run_once: True
  delegate_to: "{{ groups['rally'][0] }}"
