---

####################
## Ceph
#####################
ceph_nova_pool_type: "{{ ceph_pool_type }}"
ceph_nova_cache_mode: "{{ ceph_cache_mode }}"

# Due to Ansible issues on include, you cannot override these variables. Please
# override the variables they reference instead.
nova_pool_name: "{{ ceph_nova_pool_name }}"
nova_pool_type: "{{ ceph_nova_pool_type }}"
nova_cache_mode: "{{ ceph_nova_cache_mode }}"

# Discard option for nova managed disks. Requires libvirt (1, 0, 6) or later and
# qemu (1, 6, 0) or later. Set to "" to disable.
nova_hw_disk_discard: "unmap"

####################
## Database
#####################
nova_database_name: "nova"
nova_database_address: "{{ internal_vip_address }}:{{ mariadb_port }}"

nova_api_database_name: "nova_api"
nova_api_database_address: "{{ internal_vip_address }}:{{ mariadb_port }}"

nova_package_state: "present"
nova_logging_debug: "{{ openstack_logging_debug }}"

####################
# OpenStack
####################
nova_legacy_admin_endpoint: "{{ admin_protocol }}://{{ internal_vip_address }}:{{ nova_api_port }}/v2/%(tenant_id)s"
nova_legacy_internal_endpoint: "{{ internal_protocol }}://{{ internal_vip_address }}:{{ nova_api_port }}/v2/%(tenant_id)s"
nova_legacy_public_endpoint: "{{ public_protocol }}://{{ external_vip_address }}:{{ nova_api_port }}/v2/%(tenant_id)s"

nova_admin_endpoint: "{{ admin_protocol }}://{{ internal_vip_address }}:{{ nova_api_port }}/v2.1/%(tenant_id)s"
nova_internal_endpoint: "{{ internal_protocol }}://{{ internal_vip_address }}:{{ nova_api_port }}/v2.1/%(tenant_id)s"
nova_public_endpoint: "{{ public_protocol }}://{{ external_vip_address }}:{{ nova_api_port }}/v2.1/%(tenant_id)s"

placement_admin_endpoint: "{{ admin_protocol }}://{{ internal_vip_address }}:{{ placement_api_port }}"
placement_internal_endpoint: "{{ internal_protocol }}://{{ internal_vip_address }}:{{ placement_api_port }}"
placement_public_endpoint: "{{ public_protocol }}://{{ external_vip_address }}:{{ placement_api_port }}"

nova_services:
  nova-libvirt:
    group: "compute"
    enabled: True
    service: "libvirtd"
  placement-api:
    group: "placement-api"
    enabled: True
    service: "httpd"
  nova-api:
    group: "nova-api"
    enabled: True
    service: "openstack-nova-api"
  nova-consoleauth:
    group: "nova-consoleauth"
    enabled: True
    service: "openstack-nova-consoleauth"
  nova-novncproxy:
    group: "nova-novncproxy"
    enabled: "{{ nova_console == 'novnc' }}"
    service: "openstack-nova-novncproxy"
  nova-scheduler:
    group: "nova-scheduler"
    enabled: True
    service: "openstack-nova-scheduler"
  nova-spicehtml5proxy:
    group: "nova-spicehtml5proxy"
    enabled: "{{ nova_console == 'spice' }}"
    service: "openstack-nova-spicehtml5proxy"
  nova-serialproxy:
    group: "nova-serialproxy"
    enabled: "{{ enable_nova_serialconsole_proxy | bool }}"
    service: "openstack-nova-serialproxy"
  nova-conductor:
    group: "nova-conductor"
    enabled: True
    service: "openstack-nova-conductor"
  nova-compute:
    group: "compute"
    enabled: "{{ not enable_nova_fake | bool }}"
    service: "openstack-nova-compute"
  nova-compute-ironic:
    group: "nova-compute-ironic"
    enabled: "{{ enable_ironic | bool }}"
    service: "openstack-nova-compute"

nova_distro_packages:
  - openstack-nova-common
  - bridge-utils
  - openstack-nova-api
  - openstack-nova-conductor
  - openstack-nova-console
  - libguestfs
  - openvswitch
  - ceph-common
  - novnc
  - openstack-nova-novncproxy
  - openstack-nova-placement-api
  - openstack-nova-scheduler
  - openstack-nova-spicehtml5proxy
  - spice-html5
  - numpy
  - httpd
  - mod_wsgi

nova_compute_distro_packages:
  - openstack-nova-compute
  - bridge-utils
  - openvswitch
  - libguestfs
  - qemu-kvm
  - libvirt-daemon
  - libvirt-daemon-driver-nwfilter
  - libvirt-daemon-config-nwfilter
  - libvirt-daemon-driver-lxc
  - sysfsutils
  - ceph-common
  - genisoimage
  - iscsi-initiator-utils
  - nfs-utils
  - targetcli
  - python-rtslib
