- include: rabbitmq_cluster_create.yml
  when: >
    inventory_hostname == rabbitmq_primary_cluster_node

- include: rabbitmq_cluster_join.yml
  when: >
    inventory_hostname != rabbitmq_primary_cluster_node
