- name: Read rabbit cookie
  shell: "cat /var/lib/rabbitmq/.erlang.cookie"
  register: tmp_rabbit_cookie
  changed_when: tmp_rabbit_cookie.rc != 0
  failed_when: false

- include: rabbitmq_stopped.yml
  when: tmp_rabbit_cookie.stdout != rabbitmq_cookie_token

- name: Set rabbit cookie
  copy:
    content: "{{ rabbitmq_cookie_token }}"
    dest: /var/lib/rabbitmq/.erlang.cookie
    mode: "0400"
    owner: rabbitmq
    group: rabbitmq
  when: tmp_rabbit_cookie.stdout != rabbitmq_cookie_token
  register: cookie_set

- include: rabbitmq_started.yml
  when: tmp_rabbit_cookie.stdout != rabbitmq_cookie_token
