- name: Deploy user provided ssl cert and key
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "rabbitmq"
    group: "rabbitmq"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "{{ rabbitmq_user_ssl_cert }}", dest: "{{ rabbitmq_ssl_cert }}", mode: "0644" }
    - { src: "{{ rabbitmq_user_ssl_key }}", dest: "{{ rabbitmq_ssl_key }}", mode: "0600" }
  when: rabbitmq_user_ssl_cert is defined and rabbitmq_user_ssl_key is defined

# Deploy the user provided CA certificate as well (if the user defined it
# within /etc/openstack_deploy/user_variables.yml).
- name: Deploy user provided ssl CA cert
  copy:
    src: "{{ rabbitmq_user_ssl_ca_cert }}"
    dest: "{{ rabbitmq_ssl_ca_cert }}"
    owner: "rabbitmq"
    group: "rabbitmq"
    mode: "0644"
  when: rabbitmq_user_ssl_ca_cert is defined
