- name: Create rabbitmq config
  register: rabbit_config_changed
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "enabled_plugins.j2", dest: "/etc/rabbitmq/enabled_plugins" }
    - { src: "rabbitmq.config.j2", dest: "/etc/rabbitmq/rabbitmq.config" }
    - { src: "rabbitmq-server.j2", dest: "/etc/default/rabbitmq-server" }
    - { src: "rabbitmq-env.j2", dest: "/etc/rabbitmq/rabbitmq-env.conf" }

- include: rabbitmq_started.yml

#- name: Enable management plugin
#  rabbitmq_plugin:
#    names: rabbitmq_management
#    state: enabled
#  register: rabbitmq_plugin

- name: Enable queue mirroring
  rabbitmq_policy:
    name: "HA"
    pattern: '^(?!amq\.).*'
    tags: "ha-mode=all"
  register: rabbitmq_queue_mirror
  when: inventory_hostname == groups['rabbitmq'][0]

- name: Add OpenStack auth rabbitmq user
  rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_password }}"
    tags: "administrator"
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    state: present
  when: inventory_hostname == groups['rabbitmq'][0]

- include: rabbitmq_restart.yml
  when: >
    rabbit_config_changed|changed or rabbitmq_queue_mirror|changed

- name: Ensure default rabbitmq guest user is removed
  rabbitmq_user:
    user: guest
    state: absent
  when: inventory_hostname == groups['rabbitmq'][0]

