---
- name: Creating Neutron database
  mysql_db:
      login_host: "{{ database_address }}"
      login_port: "{{ mariadb_port }}"
      login_user: "{{ galera_root_user }}"
      login_password: "{{ galera_root_password }}"
      name: "{{ neutron_database_name }}"
  register: database
  run_once: True
  delegate_to: "{{ groups['neutron-server'][0] }}"

- name: Creating Neutron database user and setting permissions
  mysql_user:
      login_host: "{{ database_address }}"
      login_port: "{{ mariadb_port }}"
      login_user: "{{ galera_root_user }}"
      login_password: "{{ galera_root_password }}"
      name: "{{ neutron_database_name }}"
      password: "{{ neutron_database_password }}"
      host: "%"
      priv: "{{ neutron_database_name }}.*:ALL"
      append_privs: "yes"
  run_once: True
  delegate_to: "{{ groups['neutron-server'][0] }}"

- name: Perform a Neutron DB sync
  shell: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  changed_when: False
  become: yes
  become_user: neutron
  run_once: True
  delegate_to: "{{ groups['neutron-server'][0] }}"
