
- name: Create galera users
  mysql_user:
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    login_host: "{{ api_interface_address }}"
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    state: "{{ item.state }}"
  with_items:
    - name: "{{ galera_root_user }}"
      host: "%"
      password: "{{ galera_root_password }}"
      priv: "*.*:ALL,GRANT"
      state: present
    - name: "{{ galera_root_user }}"
      host: "localhost"
      password: "{{ galera_root_password }}"
      priv: "*.*:ALL"
      state: present
    - name: "haproxy"
      password: ""
      host: "%"
      priv: "*.*:USAGE"
      state: present
  register: galera_users
  until: galera_users | success
  retries: 5
  delay: 3
