- include: galera_running_check.yml
  vars:
    num_retries: 1
    wait_delay: 3

- name: Set the galera existing cluster fact
  set_fact:
    galera_existing_cluster: true
  when: mysql_running.rc == 0
