rabbitmq_primary_cluster_node: "{{ groups['rabbitmq'][0] }}"

rabbitmq_cluster_name: openstack

# Specify a partition recovery strategy (autoheal | pause_minority | ignore)
rabbitmq_cluster_partition_handling: autoheal

rabbitmq_ulimit: 4096

rabbitmq_ssl_cert: /etc/rabbitmq/rabbitmq.pem
rabbitmq_ssl_key: /etc/rabbitmq/rabbitmq.key
rabbitmq_ssl_ca_cert: /etc/rabbitmq/rabbitmq-ca.pem

rabbitmq_ssl_self_signed_regen: false
rabbitmq_ssl_self_signed_subject: "/C=CN/ST=SHENZHEN/L=nanshan/O=IT/CN=rabbit"

#rabbitmq_user_ssl_cert: <path to cert on ansible deployment host>
#rabbitmq_user_ssl_key: <path to cert on ansible deployment host>
#rabbitmq_user_ssl_ca_cert: <path to cert on ansible deployment host>

# RabbitMQ erlang VM parameters
rabbitmq_async_threads: 128
rabbitmq_process_limit: 1048576

# RabbitMQ collect statistics interval
rabbitmq_collect_statistics_interval: 5000

# RabbitMQ Management rates mode
rabbitmq_management_rates_mode: basic

rabbitmq_yum_packages:
  - rabbitmq-server
