---

- name: Install chrony packages
  package:
    name: "{{ item }}"
    state: "{{ chrony_package_state }}"
  register: install_packages
  until: install_packages | success
  retries: 5
  delay: 2
  with_items: "{{ chrony_distro_packages }}"
