---

- name: Create chrony log dir
  file:
    path: "{{ chrony_log | dirname }}"
    state: directory
    owner: "{{ chrony_user }}" 
    group: "{{ chrony_user }}"
    mode: 0755

- name: Apply chrony config
  template:
    src: "{{ chrony_conf_template }}"
    dest: "{{ chrony_conf_dest }}"
    owner: "{{ chrony_user }}" 
    group: "{{ chrony_user }}"
    mode: "0644"
  notify: Restart chrony
