---

- name: Initialise fernet key authentication
  command: keystone-manage --config-file /etc/keystone/keystone.conf fernet_setup --keystone-user keystone --keystone-group keystone
  run_once: True
  delegate_to: "{{ groups['keystone'][0] }}"

