---

- name: Creating keystone database
  mysql_db:
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    login_host: "{{ database_address }}"
    login_port: "{{ mariadb_port }}"
    name: "{{ keystone_database_name }}"
    state: "present"
  run_once: True
  delegate_to: "{{ groups['keystone'][0] }}"

- name: Grant access to the DB for the service
  mysql_user:
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    login_host: "{{ database_address }}"
    login_port: "{{ mariadb_port }}"
    name: "{{ keystone_database_user }}"
    password: "{{ keystone_database_password }}"
    host: "{{ item }}"
    state: "present"
    priv: "{{ keystone_database_name }}.*:ALL"
  with_items:
    - "localhost"
    - "%"
  run_once: True
  delegate_to: "{{ groups['keystone'][0] }}"

- name: Perform a Keystone DB sync
  command: keystone-manage db_sync
  changed_when: False
  become: yes
  become_user: keystone
  run_once: True
  delegate_to: "{{ groups['keystone'][0] }}"
