---

- name: Create memcached log dir
  file:
    path: "{{ memcached_log | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Apply memcached config
  template:
    src: "{{ memcached_conf_template }}"
    dest: "{{ memcached_conf_dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Restart memcached

- name: Override systemd service file
  copy:
    src: "{{ memcached_systemd_service }}"
    dest: "/etc/systemd/system/memcached.service"
    owner: "root"
    group: "root"
    mode: "0644"
  when: memcached_systemd_service is defined
  notify: Restart memcached

- name: Create memcached systemd service config dir
  file:
    path: "/etc/systemd/system/memcached.service.d"
    state: "directory"
    group: "root"
    owner: "root"
    mode: "0755"
  when:
    - ansible_service_mgr == 'systemd'

- name: Apply resource limits (systemd)
  template:
    src: "limits.conf.j2"
    dest: "/etc/systemd/system/memcached.service.d/limits.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - ansible_service_mgr == 'systemd'
    - memcached_connections > 1024
  notify:
    - Restart memcached

- name: Configure soft file limits
  lineinfile:
    dest: "/etc/security/limits.conf"
    regexp: "^{{ memcached_user }}.*soft.*nofile.*"
    state: "present"
    line: "{{ memcached_user }}\tsoft\tnofile\t\t{{ memcached_file_limits }}"
    insertbefore: "^# End of file"

- name: Configure hard file limits
  lineinfile:
    dest: "/etc/security/limits.conf"
    regexp: "^{{ memcached_user }}.*hard.*nofile.*"
    state: "present"
    line: "{{ memcached_user }}\thard\tnofile\t\t{{ memcached_file_limits }}"
    insertbefore: "^# End of file"
