---

- name: Install horizon packages
  package:
    name: "{{ item }}"
    state: "{{ horizon_package_state }}"
  register: install_packages
  until: install_packages | success
  retries: 5
  delay: 2
  with_items: "{{ horizon_distro_packages }}"
