---

- name: Install nova packages
  package:
    name: "{{ item }}"
    state: "{{ nova_package_state }}"
  register: install_packages
  until: install_packages | success
  retries: 5
  delay: 2
  with_items: "{{ nova_distro_packages }}"
