---

- name: Ensure nova service started
  vars:
    services_require_nova_conf:
      - placement-api
      - nova-api
      - nova-libvirt
      - nova-compute
      - nova-compute-ironic
      - nova-conductor
      - nova-consoleauth
      - nova-novncproxy
      - nova-serialproxy
      - nova-scheduler
      - nova-spicehtml5proxy
  systemd:
    name: "{{ item.value.service }}"
    state: "started"
    enabled: "{{ item.value.enabled }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
    - item.key in services_require_nova_conf
  with_dict: "{{ nova_services }}"
